### ISSUE TITLE
Please import `WizardCoder-Python` GGUF

### ISSUE THREAD

**Issue by kim0** [go-skynet/model-gallery#26]
What's the proper way to get
https://huggingface.co/TheBloke/WizardCoder-Python-34B-V1.0-GGUF
imported into the library?

Is it not showing bec it's a `gguf` model, and the scraping code is searching for `ggml` ?

**Comment by Aisuko** [comment]
Hi, guys. I believe that we already synchronized ggufv2 features though https://github.com/go-skynet/go-llama.cpp/commit/bf3f9464906790082cc049222bb5d7230f66cb52. (Will confirm later.) But we may not have a new example for how to use it.
